# Generated by Django 4.1 on 2022-08-09 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_tickets', '0002_order_date_created_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtic',
            name='date_arrival',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='airtic',
            name='date_flight',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
